### ISSUE TITLE
Please add support for ApplePi DAC

### ISSUE THREAD

**Issue by orchardaudio** [ralph-irving/tcz-squeezeplay#1]
Hello,

Please add support for the ApplePi DAC, it has already been added to raspian per my request here:
https://github.com/raspberrypi/linux/issues/2302

Here is the overlay:
[ApplePi-DAC_dtbo_dts.zip](https://github.com/ralph-irving/tcz-squeezeplay/files/1910418/ApplePi-DAC_dtbo_dts.zip)

Thanks;
Leo

**Comment by ralph-irving** [comment]
This is already available in picoreplayer 3.5.0
$ cat /usr/local/sbin/piversion.cfg 
#piCorePlayer version
PIVERS="piCorePlayer 3.5.0"
tc@rpi3p:/mnt/mmcblk0p1/overlays$ ls -l /mnt/mmcblk0p1/overlays/applepi-dac.dtbo
-rwxrwxrwx 1 tc staff 1454 Mar 23 22:42 /mnt/mmcblk0p1/overlays/applepi-dac.dtbo
